################################
# Azure Pipelines build template
################################
# Azure DevOps project: https://marshallmacy.visualstudio.com/tbrpg
# Azure Pipelines build definition: https://marshallmacy.visualstudio.com/tbrpg/_build?definitionId=1
################################

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) src/tbrpg.sln
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(buildConfiguration)'
  inputs:
    command: test
    projects: 'src/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'